/**
 * JWT/HMAC-signed webhook delivery agent for StellarSplit.
 *
 * Builds structured {@link WebhookPayload} envelopes for split-payment
 * lifecycle events, signs them with a shared HMAC-SHA256 secret, and
 * delivers them over HTTP with exponential-backoff retry. Pair with
 * {@link verifyWebhookSignature} (./verify.js) on the receiving end.
 */

import { createHmac, randomUUID } from "crypto";
import { WebhookExhaustedError } from "../errors.js";
import type { WebhookPayload } from "../types.js";

/** Header carrying the hex-encoded HMAC-SHA256 signature of the raw body. */
export const WEBHOOK_SIGNATURE_HEADER = "X-Stellar-Split-Signature";

/** Configuration for {@link WebhookAgent}. */
export interface WebhookAgentOptions {
  /** Shared secret used to HMAC-sign delivered payloads. */
  secret: string;
  /** Maximum number of retries after the initial attempt. Default: 5. */
  maxRetries?: number;
  /** Backoff cap in milliseconds. Default: 60000 (60s). */
  maxBackoffMs?: number;
  /** Override for `fetch`, primarily for testing. */
  fetchImpl?: typeof fetch;
}

/** Input for a single webhook delivery; `event_id` and `timestamp` are generated by the agent. */
export interface WebhookDeliveryInput<T> {
  /** Machine-readable event type, e.g. "invoice.payment.completed". */
  event_type: string;
  /** Event-specific data. */
  data: T;
}

/**
 * Signs and delivers webhook payloads with retry and exponential backoff.
 *
 * @example
 * ```typescript
 * const agent = new WebhookAgent({ secret: process.env.WEBHOOK_SECRET! });
 * await agent.deliver("https://consumer.example.com/hooks", {
 *   event_type: "invoice.payment.completed",
 *   data: { invoiceId, amount },
 * });
 * ```
 */
export class WebhookAgent {
  private readonly secret: string;
  private readonly maxRetries: number;
  private readonly maxBackoffMs: number;
  private readonly fetchImpl: typeof fetch;

  constructor(options: WebhookAgentOptions) {
    this.secret = options.secret;
    this.maxRetries = options.maxRetries ?? 5;
    this.maxBackoffMs = options.maxBackoffMs ?? 60_000;
    this.fetchImpl = options.fetchImpl ?? fetch;
  }

  /**
   * Delivers a signed webhook payload to `url`, retrying transient
   * failures with exponential backoff (2^n seconds, capped).
   *
   * @throws {WebhookExhaustedError} once all retries are exhausted.
   * @returns The envelope that was delivered, including its generated `event_id`.
   */
  async deliver<T>(url: string, payload: WebhookDeliveryInput<T>): Promise<WebhookPayload<T>> {
    const envelope: WebhookPayload<T> = {
      event_id: randomUUID(),
      event_type: payload.event_type,
      timestamp: new Date().toISOString(),
      data: payload.data,
    };

    const rawBody = JSON.stringify(envelope);
    const signature = signBody(this.secret, rawBody);

    let lastError: string | undefined;
    const totalAttempts = this.maxRetries + 1;

    for (let attempt = 0; attempt < totalAttempts; attempt++) {
      try {
        const response = await this.fetchImpl(url, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            [WEBHOOK_SIGNATURE_HEADER]: signature,
          },
          body: rawBody,
        });

        if (response.ok) {
          return envelope;
        }
        lastError = `HTTP ${response.status}`;
      } catch (err) {
        lastError = err instanceof Error ? err.message : String(err);
      }

      const isLastAttempt = attempt === totalAttempts - 1;
      if (!isLastAttempt) {
        await sleep(Math.min(2 ** attempt * 1000, this.maxBackoffMs));
      }
    }

    throw new WebhookExhaustedError(url, totalAttempts, lastError);
  }
}

function signBody(secret: string, rawBody: string): string {
  return createHmac("sha256", secret).update(rawBody).digest("hex");
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
